### ISSUE TITLE
Request: Implement Scroll-to-Focus on Soft Keyboard Appearance

### ISSUE THREAD

**Issue by gayanSandamal** [GFean/react-native-connected-inputs#1]
## Request: Implement Scroll-to-Focus on Soft Keyboard Appearance When There are Many Input Fields

**Description:**

When a user taps on an input field on a mobile device and keep moving the next field by pressing "Next", the soft keyboard appears and can potentially obscure the next immediate field when it's originally stays below the soft keyboard. This makes it difficult for the user to see what they are typing. 

This issue requests the implementation of a scroll-to-focus behaviour. When the soft keyboard appears and an input field is currently focused, the content area should automatically scroll to ensure the focused field remains visible above the keyboard.

**Expected Behaviour:**

* Upon tapping on an input field, the soft keyboard appears.
* The content area should automatically scroll vertically so that the focused input field remains completely visible above the keyboard when pressing "Next on the soft keyboard".

**Additional Context:**

* This feature is commonly found in mobile applications to improve user experience and prevent frustration when typing on small screens and input heavy forms.

**Please consider implementing this functionality to enhance the usability of the application on mobile devices.**

https://github.com/GFean/react-native-connected-inputs/assets/33354992/b69b522d-4baa-4f11-a5cf-81784c2af10b

**Comment by GFean** [comment]
Hello @gayanSandamal, 

Thank you for your suggestion regarding the scroll-to-focus behaviour when using multiple input fields. 
I appreciate your feedback and understand the importance of ensuring a smooth user experience when interacting with forms on mobile devices.

The `react-native-connected-inputs` package is designed specifically to connect input fields and manage their focus and submission handling. Its primary function is to ensure that when you press `Next`"on the keyboard, the focus moves to the next input field, and when you press `Done` on the last input field, a callback function is executed.

Technically, it would be possible to implement scroll-to-focus behavior within the react-native-connected-inputs package. This would involve monitoring the keyboard's appearance and dynamically adjusting the scroll position to keep the focused input field visible. However, integrating this feature directly into the package would significantly increase its complexity and size. It would also introduce additional dependencies and configuration steps, making the package less convenient to use for its primary purpose.


For managing keyboard interactions, such as ensuring that input fields remain visible when the soft keyboard appears, I recommend using additional packages that are specifically designed for this purpose. 

Some popular options include:

[react-native-keyboard-aware-scroll-view](https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view): - This package provides a KeyboardAwareScrollView component that automatically adjusts the scroll view to ensure that input fields are visible above the keyboard.
[react-native-keyboard-avoiding-view:](https://reactnative.dev/docs/keyboardavoidingview) - This package provides a KeyboardAvoidingView component that moves or resizes its children to avoid the keyboard.
[`useAnimatedKeyboard` by `react-native-reanimated`](https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/hooks/useAnimatedKeyboard/) - With this hook you can create animations based on current keyboard position.

Here is a basic example of how you can integrate `react-native-keyboard-aware-scroll-view` with `react-native-connected-inputs` to achieve the desired behaviour:

```jsx
import React from 'react';
import { SafeAreaView, TextInput, StyleSheet, Alert, Text } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import useConnectedInputs from './useConnectedInputs';

const App: React.FC = () => {
  const handleFormSubmit = () => {
    Alert.alert('Form Submitted');
  };

  const connectInput = useConnectedInputs(handleFormSubmit);

  return (
    <SafeAreaView style={styles.container}>
      <KeyboardAwareScrollView contentContainerStyle={styles.scrollContainer}>
        <TextInput style={styles.input} placeholder="First Input" {...connectInput(0)} />
        <Text>Hi there</Text>
        <TextInput style={styles.input} placeholder="Second Input" {...connectInput(1)} />
        <TextInput style={styles.input} placeholder="Third Input" {...connectInput(2)} />
        <TextInput style={styles.input} placeholder="Fourth Input" {...connectInput(3)} />
        <TextInput style={styles.input} placeholder="Fifth Input" {...connectInput(4)} />
        <TextInput style={styles.input} placeholder="Sixth Input" {...connectInput(5)} />
        <TextInput style={styles.input} placeholder="Seventh Input" {...connectInput(6)} />
        <TextInput style={styles.input} placeholder="Eighth Input" {...connectInput(7)} />
        <TextInput style={styles.input} placeholder="Ninth Input" {...connectInput(8)} />
        <TextInput style={styles.input} placeholder="Tenth Input" {...connectInput(9)} />
        <TextInput style={styles.input} placeholder="Eleventh Input" {...connectInput(10)} />
        <TextInput style={styles.input} placeholder="Twelfth Input" {...connectInput(11)} />
        <TextInput style={styles.input} placeholder="Thirteenth Input" {...connectInput(12)} />
        <TextInput style={styles.input} placeholder="Fourteenth Input" {...connectInput(13)} />
        <TextInput style={styles.input} placeholder="Fifteenth Input" {...connectInput(14)} />
        <TextInput style={styles.input} placeholder="Sixteenth Input" {...connectInput(15)} />
        <TextInput style={styles.input} placeholder="Seventeenth Input" {...connectInput(16)} />
        <TextInput style={styles.input} placeholder="Eighteenth Input" {...connectInput(17)} />
        <TextInput style={styles.input} placeholder="Nineteenth Input" {...connectInput(18)} />
        <TextInput style={styles.input} placeholder="Twentieth Input" {...connectInput(19)} />
      </KeyboardAwareScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    marginBottom: 10,
    width: '80%',
  },
});

export default App;
```

Hereby check the video demo of execution of the code above: 

https://github.com/GFean/react-native-connected-inputs/assets/37250288/262a6da7-b550-4ec7-a5a0-6dcd240eb96e


### Feedback and Future Considerations

I will keep this issue open for a while to gather more feedback from users. If many users request this feature, I may still consider developing it in the future. Your feedback is valuable to me, and I appreciate your understanding and support.

Thank you for your understanding and for using `react-native-connected-inputs`!

**Comment by gayanSandamal** [comment]
@GFean  Thank you so much for your humble response with the possibilities to make focus scroll achieved. I'm closing this ticket as it can be achieved with "react-native-keyboard-aware-scroll-view" module
